# 标题
title: MakeByMine

# 作者
author: "空白"

# 主题的语言设置
language:
  default: "zh" # 设置默认语言为中文
  # 或者使用以下方式指定多个语言
  # available: ["zh", "en"] # 支持中文和英文

menus:
    main:
        name: skylerLWW
        link: /
    Home:
        name: house
        link: /
    About:
        name: about
        link: /about
    Archives:
        name: Archives
        link: /archives
    Categories:
        name: categories
        link: /category
    Tags:
        name: tags
        link: /tag

links:
  gitee: https://www.gitee.com/SmartLWW
  github: https://www.github.com/SkylerLWW