# 标题
title: MakeByMine

# 作者
author: "空白"

# 主题的语言设置
language:
  default: "zh" # 设置默认语言为中文
  # 或者使用以下方式指定多个语言
  # available: ["zh", "en"] # 支持中文和英文

menus:
    main:
        name: skylerLWW
        link: /
    Home:
        name: house
        link: /
    About:
        name: about
        link: /about
    Archives:
        name: Archives
        link: /archives

backlinks:
  github:
    url: https://www.github.com/SkylerLWW
    icon: icon-github1
  gitee:
    url: https://www.gitee.com/SmartLWW
    icon: icon-gitee
  bilibili:
    url: https://space.bilibili.com/403796789
    icon: icon-person
  douyin:
    url: https://www.douyin.com/user/MS4wLjABAAAAYGG6UweTou5PjyzHnF1ol8CbGqkCUznzr3B9UL9jxRndU3HNhrInyX16NDRQEClq
    icon: icon-douyinzhanghao

favicon:
  href: /images/head.png # 网站图标
  type: image/png

footer:
  since: 2024
